// =============================================================
// SNN_Accelerator.sv  —  ASIC synthesis version
// Change from original (rtl/top/SNN_Accelerator.sv):
//   $readmemh("weights_conv.hex") replaced with localparam ROM
//   Run asic/scripts/gen_weights.py to fill in CONV_WEIGHTS.
// =============================================================
module SNN_Accelerator #(
    parameter int IMG_WIDTH   = 28,
    parameter int NUM_FILTERS = 8,
    parameter int DATA_WIDTH  = 8,
    parameter int ACC_WIDTH   = 18,
    parameter int V_THRESH    = 59723
) (
    input  logic       clk,
    input  logic       rst_n,
    input  logic       frame_rst_n,
    input  logic       s_axis_valid,
    output logic       s_axis_ready,
    input  logic [7:0] s_axis_data,
    output logic       m_axis_valid,
    output logic [NUM_FILTERS-1:0] m_axis_spike,
    output logic       m_frame_done
);

    // ---------------------------------------------------------
    // Conv weights as localparam ROM (synthesis-safe, Yosys-compatible)
    // 8 filters x 9 taps = 72 signed 8-bit values packed into 576 bits.
    // Stored LSB-first: weight[i] = CONV_WEIGHTS_FLAT[i*8 +: 8]
    // Concatenation lists index 71 first so index 0 lands at bit [7:0].
    // Generated by: python3 asic/scripts/gen_weights.py
    // ---------------------------------------------------------
    localparam [575:0] CONV_WEIGHTS_FLAT = {
        8'h1E, 8'h2D, 8'hB0, 8'hE0, 8'hBA, 8'h25, 8'hED, 8'h0F, 8'hE8,  // f7 idx71..63
        8'hF1, 8'hA5, 8'hE2, 8'hA7, 8'h21, 8'hE8, 8'hF5, 8'h03, 8'hFE,  // f6 idx62..54
        8'h10, 8'h8C, 8'hBD, 8'h96, 8'hED, 8'h77, 8'h58, 8'h72, 8'h1C,  // f5 idx53..45
        8'h3E, 8'h69, 8'h3D, 8'hF0, 8'h2E, 8'hD9, 8'h13, 8'h51, 8'hEE,  // f4 idx44..36
        8'h5D, 8'h24, 8'h44, 8'h2F, 8'hEA, 8'h72, 8'h8B, 8'hE6, 8'hBD,  // f3 idx35..27
        8'hCF, 8'hC9, 8'hB5, 8'h17, 8'hD4, 8'h04, 8'hB9, 8'h0D, 8'hEC,  // f2 idx26..18
        8'h17, 8'h50, 8'hED, 8'h4A, 8'h25, 8'h1C, 8'h33, 8'h4F, 8'h81,  // f1 idx17..9
        8'h3C, 8'h2C, 8'hCC, 8'hFD, 8'h0A, 8'h62, 8'hDC, 8'h6B, 8'h59   // f0 idx8..0
    };

    // ---------------------------------------------------------
    // Internal signals (unchanged from original)
    // ---------------------------------------------------------
    logic                  lb_valid;
    logic [8:0][7:0]       lb_window;
    logic                  o_skip;
    logic                  o_fire_enable;
    logic                  fsm_clear_mem;
    logic [9:0]            vmem_addr;
    logic [9:0]            waddr_q;

    logic signed [ACC_WIDTH-1:0] vmem_read_data  [0:NUM_FILTERS-1];
    logic signed [ACC_WIDTH-1:0] vmem_write_data [0:NUM_FILTERS-1];
    logic                        pe_vmem_valid   [0:NUM_FILTERS-1];

    // Weight array wired from localparam (replaces $readmemh)
    logic signed [8:0][7:0] weights_mem [0:NUM_FILTERS-1];
    genvar gw, kw;
    generate
        for (gw = 0; gw < NUM_FILTERS; gw = gw + 1) begin : GEN_W_FILTER
            for (kw = 0; kw < 9; kw = kw + 1) begin : GEN_W_TAP
                assign weights_mem[gw][kw] = signed'(CONV_WEIGHTS_FLAT[(gw*9+kw)*8 +: 8]);
            end
        end
    endgenerate

    assign s_axis_ready = 1'b1;

    // ---------------------------------------------------------
    // Submodule instantiations (unchanged from original)
    // ---------------------------------------------------------
    LineBuffer #(.IMG_WIDTH(IMG_WIDTH), .DATA_WIDTH(DATA_WIDTH)) u_linebuffer (
        .clk    (clk),
        .rst_n  (frame_rst_n),
        .i_valid(s_axis_valid & s_axis_ready),
        .i_data (s_axis_data),
        .o_valid(lb_valid),
        .o_window(lb_window)
    );

    SparsityController u_sparsity (
        .i_window     (lb_window),
        .i_valid      (lb_valid),
        .o_skip       (o_skip),
        .o_fire_enable(o_fire_enable)
    );

    TimeStep_FSM u_fsm (
        .clk        (clk),
        .rst_n      (rst_n),
        .i_lb_valid (lb_valid),
        .o_clear_mem(fsm_clear_mem),
        .o_vmem_addr(vmem_addr),
        .o_frame_done(m_frame_done)
    );

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) waddr_q <= '0;
        else if (lb_valid) waddr_q <= vmem_addr;
    end

    genvar gi;
    generate
        for (gi = 0; gi < NUM_FILTERS; gi = gi + 1) begin : GEN_PE_CHANNEL
            Vmem_Array #(.ACC_WIDTH(ACC_WIDTH)) u_vmem (
                .clk    (clk),
                .i_we   (pe_vmem_valid[gi]),
                .i_raddr(vmem_addr),
                .i_waddr(waddr_q),
                .i_wdata(vmem_write_data[gi]),
                .o_rdata(vmem_read_data[gi])
            );

            ConvPE #(
                .DATA_WIDTH(DATA_WIDTH),
                .ACC_WIDTH (ACC_WIDTH),
                .V_THRESH  (V_THRESH)
            ) u_pe (
                .clk         (clk),
                .rst_n       (rst_n),
                .i_valid     (lb_valid),
                .i_clear_mem (fsm_clear_mem),
                .i_vmem_read (vmem_read_data[gi]),
                .i_window    (lb_window),
                .i_weights   (weights_mem[gi]),
                .i_skip      (o_skip),
                .o_spike     (m_axis_spike[gi]),
                .o_vmem_valid(pe_vmem_valid[gi]),
                .o_vmem_write(vmem_write_data[gi])
            );
        end
    endgenerate

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) m_axis_valid <= 1'b0;
        else        m_axis_valid <= lb_valid;
    end

endmodule
